### ISSUE TITLE
debian_installer: support for mmcblk drives

### ISSUE THREAD

**Issue by dcbaker** [janesma/mesa_jenkins#25]
currently if the debian installer needs to be pointed at non /dev/sda (such as /dev/mmcblk0) the installs script must be modified and a new image created. It would be ideal if autodetection could happen to set this correctly

**Comment by janesma** [comment]
Dylan's latest installer implements this.

**Comment by dcbaker** [comment]
I don't think it does actually. Ideally we could have one image that was smart enough to detect the correct location without having to create two separate installers for mmcblk0 and sda.

I'm hoping that we can have a script that runs as an early hook to determine this for us.

**Comment by dcbaker** [comment]
Actually, I think I've construed two different problems in this issue, I'll open a new issue.
