### ISSUE TITLE
jenkins: bisect_mesa description mismatch

### ISSUE THREAD

**Issue by dcbaker** [janesma/mesa_jenkins#30]
The page for bisect mesa failures says: 
```sha of the mesa build which did not have the failures.  Just pass the sha, do not include the "mesa="```

However, the script clearly expects to be passed '<project>=<sha>'.

**Comment by janesma** [comment]
sorry about that.  There used to be two projects, one for bisecting mesa, and the other for bisecting piglit.

I combined them, but left the old comment.  It's fixed now.
